// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "apiProvider": string;
      "trackArxiv": boolean;
      "trackPubmed": boolean;
      "profileMode": string;
      "pythonServerStartCommand": string;
      "enableDailyPush": boolean;
      "categories": string;
      "keywords": string;
      "authors": string;
      "maxResults": number;
      "relevanceThreshold": number;
      "shortcutKey": string;
    };
  }
}
